import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nest Mart | Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children, header, footer, dashbord
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
  dashbord: React.ReactNode;
}>) {
  return (
    <main>
      {header}
      <div className="relative">
        {dashbord ? dashbord : children}
      </div>
      {footer}
    </main>
  );
}
