import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Nest Mart | Dashbord",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <div className="flex gap-5">
                <div className="w-3/12">
                    <div className="flex flex-col gap-3 border border-gray rounded-lg p-5 shadow-lg">
                        <Link className="py-4 px-10 bg-primary-light rounded-lg" href="/admin">Dashbord</Link>
                        <Link className="py-4 px-10 bg-primary-light rounded-lg" href="/admin/categories">Categories</Link>
                        <Link className="py-4 px-10 bg-primary-light rounded-lg" href="/admin/products">Products</Link>
                    </div>
                </div>
                <div className="w-9/12 p-5 border border-gray rounded-lg shadow-lg">
                    {children}
                </div>
            </div>
        </section>
    );
}
