import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const quicksand = localFont({
  src: "./fonts/Quicksand-Regular.ttf",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Nest Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${quicksand.variable} antialiased`}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
