import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import AuthProvider from "@/context/AuthProvider";

const quicksand = localFont({
  src: "./fonts/Quicksand-Regular.ttf",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Nest Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={` ${quicksand.variable} antialiased`}>
          {children}
        </body>
      </AuthProvider>

    </html>
  );
}
