import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Nest Mart | Home",
  description: "Generated by create next app",
};

export default function WebLayout({
  children, header, footer, navbar
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  return (
    <main>
        {header}
        {navbar}
        {children}
        {footer}
    </main>
  );
}
